apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
     app: demo-voting-app
     name: postgres-pod
  template:
   metadata: 
     labels: 
      app: demo-voting-app
      name: postgres-pod
     name: postgres-pod
   spec: 
    containers: 
    - 
      image: postgres
      name: postgres
      env:
      - name: POSTGRES_USER
        value: admin
      - name: POSTGRES_PASSWORD
        value: admin
      ports: 
        - 
          containerPort: 5432
