apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
     app: demo-voting-app
     name: result-app-pod
  template:
   metadata: 
    labels: 
     app: demo-voting-app
     name: result-app-pod
    name: result-app-pod
   spec: 
    containers: 
    - 
      image: dockersamples/examplevotingapp_result
      name: result-app
      ports: 
        - 
          containerPort: 80